---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecare1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecare1
      tier: frontend
  template:
    metadata:
      labels:
        app: ecare1
        tier: frontend
    spec:
      containers:
        - name: app
          image: 732799771072.dkr.ecr.us-east-1.amazonaws.com/ecare_angular:latest
          ports:
            - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: ecare1
spec:
  selector:
    app: ecare1
    tier: frontend

  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
